[package]
name = "cassowary-cli"
description = "Cassowary binary"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cassowary"
path = "src/main.rs"

[dependencies]
cassowary-core.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync"] }

# logging
log.workspace = true

# CLI
clap = { version = "4.3.17", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
